### ISSUE TITLE
gr-soapy sink block failure

### ISSUE THREAD

**Issue by epiq-dhelm** [dicta/gr-soapy#2]
Hello,

I am attempting to use GNURadio 3.8 and gr-soapy to be able to gain access to an SDR that currently does not support GNURadio 3.8.  

I can run the source block fine, but the sink block no luck.

I am using the master branch of gr-soapy, and I see this error when gnuradio-companion runs:

sidekiq@sidekiq-desktop:~/SoapySidekiq/tests$ gnuradio-companion sinkGRint.grc
<<< Welcome to GNU Radio Companion 3.8.1.0 >>>

Block paths:
/usr/share/gnuradio/grc/blocks
/usr/local/share/gnuradio/grc/blocks

Loading: "/home/sidekiq/SoapySidekiq/tests/sinkGRint.grc"
>>> Done

Generating: '/home/sidekiq/SoapySidekiq/tests/top_block.py'
>>> Warning: This flow graph contains a throttle block and another rate limiting block, e.g. a hardware source or sink. This is usually undesired. Consider removing the throttle block.

Executing: /usr/bin/python3 -u /home/sidekiq/SoapySidekiq/tests/top_block.py

Traceback (most recent call last):
  File "/home/sidekiq/SoapySidekiq/tests/top_block.py", line 326, in <module>
    main()
  File "/home/sidekiq/SoapySidekiq/tests/top_block.py", line 304, in main
    tb = top_block_cls()
  File "/home/sidekiq/SoapySidekiq/tests/top_block.py", line 121, in __init__
    self.soapy_sink_0 = soapy.sink(1, dev, ' ', sample_rate, "sc16", ' ')
  File "/usr/local/lib/python3/dist-packages/soapy/soapy_swig.py", line 708, in make
    return _soapy_swig.sink_make(*args, **kwargs)
RuntimeError: gr::io_signature(3)

>>> Done (return code 1)

What I see is that the soapy_swig.py file created  by the gr-soapy build lists 5 parameters into the sink constructor (in the comments), but the actual code is sending in 6.  The c++ code in lib, shows that it wants 6 parameters, and the grc yml file  shows it calling it with 6.  

So I am unsure what is going on.  Any ideas?

I was going to attach the soapy_swig.py file but I don't see a way to add attachments here.

Thanks,

Dave

**Comment by dicta** [comment]
This repo is a mirror of a fairly old version of gr-soapy for use with Ubuntu 18.04, which ships GNU Radio 3.7. I'm not one of the maintainers of the upstream project.

For GNU Radio 3.8.x, you're probably looking for a release of https://gitlab.com/librespacefoundation/gr-soapy after v2.0.
For GNU Radio 3.9.x or newer, this is now integrated in GNU Radio itself and doesn't need an OOT module any longer.

**Comment by epiq-dhelm** [comment]
I did get the code from gitlab not github, but I don't have a gitlab
account and saw it here so I put comment in here.
